### ISSUE TITLE
rash vs rash/out

### ISSUE THREAD

**Issue by lehitoskin** [willghatch/racket-rash#1]
Not sure if you've noticed this yet, but `rash` will error out on any command (`rash/out` works just fine).

```
~> racket
Welcome to Racket v6.7.
> (require rash)
> (rash/out "ls | wc -l")
"15\n"
> (rash "ls | wc -l")
15
#<pipeline:success=#t,return=0>

> ; error writing to stream port
;   system error: Broken pipe; errno=32
; [,bt for context]
,bt
; error writing to stream port
;   system error: Broken pipe; errno=32
;   context...:
;    /usr/share/racket/collects/racket/private/port.rkt:129:15: loop
;    /usr/share/racket/collects/racket/private/port.rkt:123:4: loop
;    /home/lehi/.racket/6.7/pkgs/shell-pipeline/shell/pipeline.rkt:512:31
>
```

**Comment by willghatch** [comment]
Yes, thank you.  This is an error in shell/pipeline (still my package), when the input port (in this case `(current-input-port)` which is `readline-port`) is a non-`file-stream-port` (IE not a file or an OS pipe) and the first (or only) member of the shell pipeline is a process (not a closure).  When this happens I spawn the subprocess in a way that gives me an OS pipe for its input and I use `copy-port` to copy the input from the initial pipeline input port to the port I get representing the OS pipe.  However, when the pipe is closed `copy-port` will still read from the input port and try to write, which causes the file stream error.

I'm not sure what a good solution is.  I need to only read the input port if I can also write to the output port, but I have no idea how to do that.  I've tried using a read event with a port-closed event for the output port, but not all ports support events (specifically `readline-port` doesn't).  I can catch the write error and keep it from printing.  But it would still eat some input, and just do it silently, so I don't want to do that.

**Comment by lehitoskin** [comment]
Seems to be fixed since the latest changes.
