### ISSUE TITLE
Should the repl try to run a racket function if an external command doesn't exist?

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#16]
for example if you type:
```
display "hi"
```
and there's no external `display` command, should rash look for a racket function instead?  I'm not sure of the implications, but it could help the user run racket code in a more "shell-like" way.

**Comment by dieggsy** [comment]
This might be a useful option - I stumbled into this when realizing `exit` didn't work, and I had to do `(exit)`.

**Comment by vityou** [comment]
That's how I thought of it too.  A kind of workaround you can do for exit is make a line macro called quit or something, I'm not sure if there's a way to name it exit due to circular deffinitions.  You can also do `|> exit`, but that's not very easy to type.

**Comment by willghatch** [comment]
So you can do this with a different pipeline operator, and you can set the default to be different ones.  The way to set  the top-level default in the repl is with a jenky set! command, but I hope to improve that at some point.  In general it is a syntax parameter.  Check out the `=obj-if-def/unix-if-undef=` operator in the `shell-pipeline/demo/more-pipeline-operators.rkt` file.

Perhaps something like that should be the default, but I'm somewhat hesitant to do that.

**Comment by willghatch** [comment]
(I always use the `C-d` keystroke instead of `(exit)`...)

**Comment by vityou** [comment]
Stupid question, but how would I go about setting the top level as you mention?  I tried:
```
(set! #%top =obj-if-def/unix-if-undef=)
; and
(set! default-pipeline-starter =obj-if-def/unix-if-undef=)
```
but it says bad syntax.

**Comment by willghatch** [comment]
*sigh*  Sorry I wasted your time with that -- somehow I thought it was documented, and I was sleepy.  The form is `(set-default-pipeline-starter! new-starter)`.

**Comment by willghatch** [comment]
I have various thoughts about different ways I might do it going forward, but they are still a little nebulous and I put that one in just to have *something* available.

**Comment by vityou** [comment]
Something I noticed when using `=obj-if-def/unix-if-undef=` is that aliases are counted as identifiers, so it tries to run them using `=object-pipe=` which doesn't support macros as the first arg.  Maybe something like `=unix-if-supported/otherwise-racket=` would be a good default, although I'm not sure how that would be implemented nicely, and not something like: try to run it with unix and if it fails, try to run it in racket.

**Comment by vityou** [comment]
I think it should prefer the executable over an identically named racket function, at least in the repl, since it's easier and more Intuitive to type `(racket-function)` that it is to type `=unix-pipe= external-command`

**Comment by willghatch** [comment]
As I said about stuff in the demo directories -- half baked.  But it wouldn't be too hard to get it to recognize aliases.

But the question of when to prefer what is one of the things keeping me from wanting it as a default.  If you let any bound Racket identifier defer to `=object-pipe=` but you've imported something that happens to conflict with a command name that's annoying.  But I think it would be even worse to check first if a program of the right name exists -- if you add a program to your path that happens to have the same name as a function you are using in a script, suddenly your script breaks.

**Comment by willghatch** [comment]
That's also one of the reasons aliases exist (because frankly you could define aliases as pipeline operators instead) is to be able to define a set of Racket functions that you want to use without specifying a different pipeline operator without having the wonky behavior of an operator that checks if a program exists.

**Comment by vityou** [comment]
Yeah, the more I think about it, merging external programs and racket functions sounds like a bad idea.  It's easy enough to make a line macro that can run racket functions.
