### ISSUE TITLE
Feature Requests: Tab Completion + File Coloring

### ISSUE THREAD

**Issue by lehitoskin** [willghatch/racket-rash#2]
I didn't see it in the TODO file, so I figured I'd mention these two. Their importance and usefulness seems to be self-explanatory if you're writing a shell.

**Comment by willghatch** [comment]
Thanks.  Right now I'm actually in the middle of a major rewrite (on the `newrash` branch).  Basically what's in the master branch right now was my original pass at a shell -- just making something like bash available to be embedded in racket (or embed racket in it).  But then I decided to redesign it to more easily mix processes and racket functions, and make it a nice shell for pipelines of objects and for racket-only pipelines.  There is no documentation for it yet, but basically everything in the current master branch will change.  I should probably put something in the TODO or README in the master branch to that effect.

As to the issue, completion is a large project that I absolutely plan to tackle at some point, but I'm not sure when or exactly what it will look like right now.  File coloring is actually a feature of `ls` (if I correctly understand what you mean by file coloring).  In the default configuration most OSes ship for their shell, `ls` is usually an alias for `ls --color=auto`.  In rash you will be able to do it similarly.

**Comment by lehitoskin** [comment]
Ah, I see. I look forward to see the new changes!

**Comment by willghatch** [comment]
FYI, there is now tab completion in `rash-repl`, though you need the git version of the `readline-lib` package for it.

**Comment by willghatch** [comment]
Also, if by file-coloring you mean syntax highlighting of the line you are typing, a la fish, zsh-with-highlighting-plugin, etc, that probably will have to wait for some future day when there is a good line editor (well, hopefully a general emacs-style editor that is flexible enough to be embedded in different contexts including as a line editor) in Racket proper.
