### ISSUE TITLE
maybe confusing behavior with line-macro syntax class

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#28]
I'm defining a line macro called `slm` with the goal being to have an easy way to create line macros:

```
; stands for "simple line macro"
(define-line-macro slm
  (syntax-parser
    ; if lm is defined in the form `slm name = (blah x y)`
    [(_ name:id (~datum =) (~and value:expr (~not line-macro)))
     #'(define-line-macro name
         (syntax-parser
           [(_) #'value]))]
    ; if lm is defined with multiple things after `=` ex: `slm name = blah x y`
    ; it just wraps them in parentheses so it would become `(blah x y)`
    [(_ name:id (~datum =) first-thing ...)
     #'(define-line-macro name
         (syntax-parser
           [(_) #'(first-thing ...)]))]))
```

The idea is to minimize parentheses, so I'm trying to make it so that line macros that look like expressions, like `cd` with no arguments fall through to the second clause, and normal expressions like `(display "hi")` are handled by the first clause.  This works pretty well, until it encounters a line macro wrapped in parentheses, like `(cd)` or `(cd ..)`.  Apparently it recognizes them as line macros so they fall through to the second clause and are wrapped in too many parentheses.  I would have thought that they would be recognized as expressions and not line macros since they aren't straight like macros and are wrapped in parentheses.

I would like to avoid having to force the user to only provide s-expressions as values for their macros if possible.

**Comment by willghatch** [comment]
It is always matching the second case and not the first.  The problem is that `line-macro` as used in `(~not line-macro)` is not being used as a syntax class name by syntax-parse, but just as a pattern variable.  Therefore it matches anything, and so the `~not` is always false.  You can fix it by using `(~not x:line-macro)` (being sure to `(require (for-syntax linea/line-macro-prop))`.

**Comment by willghatch** [comment]
Also, I see you uploaded your rash-files repo.  Let me make a suggestion regarding syntax-parse.  You seem to often have a syntax parser with a case that includes a literal `=` as well as a case that doesn't.  You can combine them into one case by using `(~optional (~datum =))`.

**Comment by vityou** [comment]
Ah thanks.  Does the `~not` not care what name you use before the `:line macro`?  And thanks for pointing out the `~optional` pattern, I will make sure to fix that.

**Comment by willghatch** [comment]
Any name works.  You can also use the `~var` form to match against syntax classes, which provides more flexibility but is a little more verbose.
