### ISSUE TITLE
Is there a way to set the default line macro?

### ISSUE THREAD

**Issue by vityou** [willghatch/racket-rash#29]
There's `set-default-pipeline-starter!` for the run-pipeline macro, but is there any way to set the default line macro?  In racket you can re-define-syntax `#%app`, but I haven't been able to redefine `#%linea-default-line-macro`.

**Comment by willghatch** [comment]
I just hadn't bothered adding it yet -- the implicit pipeline operator insertion is older than line macros, and when I crystallized the design more and introduced line macros I didn't bother to add a similar thing in the interactive environment.  Now I have, `set-default-line-macro!`.

Both `set-default-line-macro!` and `set-default-pipeline-starter!` will probably change once I've decided a better way of going about it.  But there is a blessed way of setting it for sub-forms -- `with-default-line-macro` or `with-rash-config`.  Don't set `#%linea-default-line-macro` directly -- I have a plan to change that and make it more hygienic (so the symbol isn't directly visible, etc).
