### ISSUE TITLE
Support or document glob expansion suppression

### ISSUE THREAD

**Issue by Reilithion** [willghatch/racket-rash#47]
I can't find a convenient way to suppress glob expansion. If I want to run find, for example:

find /usr/include -iname *.h

It seems I have to escape to Racket in order to prevent the *.h from being expanded:

find /usr/include -iname (values "*.h")

In other shells, I would just use single quotes. This seems like a common thing to want to do, even with programs besides find.

**Comment by willghatch** [comment]
Thanks for reminding me.  You quote (IE lisp quote) things to stop expansion.  Eg. `find /usr/include -iname '*.h`.  Note there is only one quotation mark.  I don't think I ever did write that in the docs, so I'll do it now.

**Comment by Reilithion** [comment]
Thanks! Also, I think Rash is pretty awesome. I hope it grows up into something widely used and loved.

**Comment by willghatch** [comment]
Thanks!  It needs a lot of work before I could see it gaining any mass appeal, but I hope at least some people find it useful for now.
