### ISSUE TITLE
remove --color=auto ls alias from default demo/setup?

### ISSUE THREAD

**Issue by jbclements** [willghatch/racket-rash#48]
On OS X, 'ls' does not support a '--color=auto' switch. This means that importing demo/setup (or shell/demo/more-pipeline-operators) makes 'ls' stop working. One easy hack is just to remove the alias for 'ls' in a fork, but this seems likely to bite any Mac users that try to use the code. Ultimately, of course, things like 'in-dir' and '=filter=' should be moved out of the demo, but in the short term, would it make sense to comment this alias out? 

I'd be happy to make this as a pull request, but I don't want to bother if it doesn't make sense to others.

**Comment by willghatch** [comment]
I had commented out the aliases in the other demo file and must have simply forgotten that one.  I'll comment it out right now.

**Comment by jbclements** [comment]
In my code spelunking, it looks like it's commented out once but not in another place.

**Comment by jbclements** [comment]
Specifically:

https://github.com/willghatch/racket-rash/blob/d366b22ee854c098d656c2e45c0697f97d6f7032/shell-pipeline/demo/more-pipeline-operators.rkt

**Comment by jbclements** [comment]
(You probably already knew that....)

**Comment by willghatch** [comment]
Fixed.  Although I guess I should have let you make a pull request to inflate my contributor count and create an illusion that more work is happening...

**Comment by willghatch** [comment]
Thanks for letting me know about that.  Keep the issues coming if you see anything else you want improved.

**Comment by jbclements** [comment]
thanks!
