### ISSUE TITLE
When typing non latin chars in REPL - get "¼Ð³Ð¼Ð¾ÑÐ"

### ISSUE THREAD

**Issue by Nyanraltotlapun** [willghatch/racket-rash#51]
When typing non latin chars in REPL - get "¼Ð³Ð¼Ð¾ÑÐ"
Steps to reproduce:
1. Install Dr. Racket 
2. raco pkg install rash
3. run in terminal emulator racket -l rash/repl
4. try to type non latin chars

Tested on Manjaro Linux and FreeBSD in xterm qterminal and xfce terminal

**Comment by willghatch** [comment]
Have you done `raco pkg install readline-gpl`?  If not does it fix the problem?

The issue is in the documentation, but it's not very obviously placed.  I'll try to make it more obvious.  In the future I plan a better fix (by using a different line editor).

**Comment by willghatch** [comment]
I've tried to make the issue stand out a little better in the documentation.  Would it be more helpful if there were a more clear FAQ section, perhaps?

**Comment by Nyanraltotlapun** [comment]
> Have you done `raco pkg install readline-gpl`? If not does it fix the problem?
Yes, it is fix the problem.
Thank you!

>Would it be more helpful if there were a more clear FAQ section, perhaps?
I think reasonable to write this in installation instruction.
So user will be aware as soon as possible.

I wonder is there a really license issue witch readline?
Because it is already installed in the system and user already accepted gpl license...

**Comment by willghatch** [comment]
On Wed, Apr 03, 2019 at 10:37:07PM -0700, Nyanraltotlapun wrote:
>>Would it be more helpful if there were a more clear FAQ section, perhaps?
>
>I think reasonable to write this in installation instruction.
>So user will be aware as soon as possible.

That's a good point.  It is now there.

>I wonder is there a really license issue witch readline?
>Because it is already installed in the system and user already accepted gpl license...

I think that distributing it in such a way that it will always link against a GPL-licensed library would require it to be GPL-ed.  But I'm not a lawyer.  At any rate, the Racket leaders want to relicense to permissive licenses (Apache/MIT or something).

As far as line editing goes, though, my medium-term plan is to write a new line editor for Racket (possibly re-purposing one of the Remacs or Rmacs packages).
