### ISSUE TITLE
Can't exit shell on Mac OS X

### ISSUE THREAD

**Issue by nwg** [willghatch/racket-rash#87]
Hello. I am having trouble exiting rash on Mac OS X. I haven't debugged it too in-depth yet but here is what happens.

I open the shell. I hit ^D on my keyboard. I get this:

```
> ^Dput-preferences: some other process has the preference-file lock, as indicated by the existence of the lock file: #<path:/Users/griswold/Library/Preferences/.LOCKorg.racket-lang.prefs.rktd>
  context...:
   /Applications/Racket/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   /Applications/Racket/collects/racket/file.rkt:426:0: call-with-file-lock
   /Applications/Racket/share/pkgs/readline-lib/readline/pread.rkt:197:23
```

I tried both exiting back to zsh and exiting from an `exec`d rash-repl. I've tried both `rash-repl` indirectly and manual `racket -l rash/repl`.

I don't know anything about the mac os x preference file lock, so i can't be of much help until i look into what is actually happening here. Exiting on my linux box is fine, so maybe people just haven't tested rash on os x yet, or maybe there is something wrong with my system. In any case, thought i would report so there is a log for anyone who runs into this to see.

Big Sur 11.3.1 (20E241)

**Comment by nwg** [comment]
Hm, this isn't really a rash issue, it's happening for me in regular racket v8.1 [cs], too.

**Comment by willghatch** [comment]
This happens on Linux too.  I'm also unsure what causes this, but it's a nuisance.  It is due to use of the readline FFI library.  At any rate, as with most other issues on the tracker, my ultimate solution will be to write a new racket-native line editor.  Eventually...
