### ISSUE TITLE
How to build documentation?

### ISSUE THREAD

**Issue by Bost** [willghatch/racket-rash#89]
Hi. Could you please provide instructions how to build documentation? Following doesn't work:

```bash
$ scribble +m rash/scribblings/rash.scrbl
 [Output to rash.html]
Warning: some cross references may be broken due to undefined tags:
 (dep ((lib "rash/private/lang-funcs.rkt") rash))
 (dep ((lib "rash/private/lang-funcs.rkt") run-pipeline))
 (dep ((lib "rash/private/top-level-print.rkt") current-rash-top-level-print-formatter))
 (dep ((lib "rash/private/lang-funcs.rkt") splicing-with-rash-config))
 (dep ((lib "shell/private/pipeline-macro-parse.rkt") splicing-with-pipeline-config))
 (dep ((lib "rash/private/cd.rkt") cd))
 (dep ((lib "rash/private/lang-funcs.rkt") current-rash-top-level-print-formatter))
 (dep ((lib "rash/private/lang-funcs.rkt") make-rash-transformer))
 (dep ((lib "rash/private/lang-funcs.rkt") with-rash-config))
 (dep ((lib "rash/private/lang-funcs.rkt") splicing-with-pipeline-config))
 (dep ((lib "rash/main.rkt") splicing-with-pipeline-config))
 (dep ((lib "rash/private/lang-funcs.rkt") cd))
```
See also https://racket.slack.com/archives/C06V96CKX/p1622290281285300
Thanks

**Comment by willghatch** [comment]
I always build the documentation (assuming the git version) by:

(1) installing the package (from git)

```
cd $RASH_PACKAGE_DIRECTORY
raco pkg install
```

This should build the documentation as it exists in the git repository.  Note that you need `shell-pipeline` and `linea` packages (in the same repo) installed before doing that.  You can also use `raco pkg install rash --clone`, or something like that, to clone the repo and install from git.

(2) Later after I edit the documentation, I build them using `raco setup`

Using `raco setup` with no arguments builds all packages, though, and takes a long time.  (I rather wish that were done by `raco setup --all` or something, with a bare `raco setup` giving a usage message.)  So I do `raco setup --pkgs rash` to build just the rash docs.  Of course, this builds everything, not just the docs, but... I just haven't been bothered enough to learn how to build just the docs.  Some `scribble` command should do it... but I imagine `raco setup` provides it with various flags to put it in the right place among the other documentation, and I haven't tried to figure out what those may be.  You can probably find it by reading the source of `raco setup` or something, or maybe asking on the mailing list.

(Note that sometimes it's nice to build the code without building the docs, and when I do that I use the `--no-docs` flag for `raco setup`.)

**Comment by Bost** [comment]
Thanks for the response. It looks like `raco setup pkg rash` also works, when started from the $RASH_CODE directory when I clone it with `git clone https://github.com/willghatch/racket-rash.git $RASH_CODE`.
