### ISSUE TITLE
multi-line readline prompt with ansi-escapes

### ISSUE THREAD

**Issue by LordMZTE** [willghatch/racket-rash#93]
I'm using a custom-made prompt which is implemented as a command. It uses ANSI escape codes and spans 2 lines.
I have rash set up to use the `readline-gpl` library.
This is my attempt at configuring this in rash:
```racket
#lang rash
(require
  racket/port
  rash/private/rashrc-lib
  readline/pread)

(current-prompt-function
  (λ ()
    (readline-prompt #{prompt show 0 insert |> port->bytes})))
```
The issue is that readline seems to filter out the ANSI escapes as well as newlines. The following screenshot illustrates how this prompt looks in fish as well as how it ends up looking in rash:
![image](https://user-images.githubusercontent.com/28735087/218282366-0eccaf61-5d9f-458e-9ee8-4c93626e4c36.png)
How can I make the prompt display correctly, while also remaining compatible with readline?

**Comment by willghatch** [comment]
Is the `prompt` command you are using available somewhere?  If I put that same code in a repl, or in `rashrc.rkt` or `rashrc` but replace the `prompt show 0 insert` command with `echo -n -e "\e[39;42mhello\e[0m\n>"`, I get a `hello` with a green background like I expect on the first line, then a `>` on the second line.  So I'm not immediately able to reproduce this.

What operating system are you using?

**Comment by LordMZTE** [comment]
I'm running Arch Linux. I wrote the prompt myself, the source is available [here](https://mzte.de/git/LordMZTE/dotfiles/src/branch/master/scripts/prompt). However, I wouldn't recommend building it, as it requires a pretty exotic compiler toolchain, and the build system is currently broken anyways. I doubt my command produces incorrect output, as there are no checks in place, and if I run `prompt show 0 insert | cat` (which would make a potential `isatty` call return false), it still shows ANSI escapes.

If I adjust my config with your echo command, I still get broken output:
```
39;42mhello[0m>
```

**Comment by LordMZTE** [comment]
Looks like I had incorrectly installed the readline-gpl package, causing the wrong library to be used. Sorry about that!
